# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Petr/Xilinx/Mandelbrot/designs/vivado/mandelbrot_pinout/2018.2/mandelbrot_pinout.srcs/sources_1/ip/bram_video_memory_wauto_dauto_rdclk1_wrclk1/bram_video_memory_wauto_dauto_rdclk1_wrclk1.xci
# IP: The module: 'bram_video_memory_wauto_dauto_rdclk1_wrclk1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Petr/Xilinx/Mandelbrot/designs/vivado/mandelbrot_pinout/2018.2/mandelbrot_pinout.srcs/sources_1/ip/bram_video_memory_wauto_dauto_rdclk1_wrclk1/bram_video_memory_wauto_dauto_rdclk1_wrclk1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_video_memory_wauto_dauto_rdclk1_wrclk1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Petr/Xilinx/Mandelbrot/designs/vivado/mandelbrot_pinout/2018.2/mandelbrot_pinout.srcs/sources_1/ip/bram_video_memory_wauto_dauto_rdclk1_wrclk1/bram_video_memory_wauto_dauto_rdclk1_wrclk1.xci
# IP: The module: 'bram_video_memory_wauto_dauto_rdclk1_wrclk1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Petr/Xilinx/Mandelbrot/designs/vivado/mandelbrot_pinout/2018.2/mandelbrot_pinout.srcs/sources_1/ip/bram_video_memory_wauto_dauto_rdclk1_wrclk1/bram_video_memory_wauto_dauto_rdclk1_wrclk1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_video_memory_wauto_dauto_rdclk1_wrclk1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
